[package]
name = "gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
forms = { path = "../../forms" }
log.workspace = true
env_logger.workspace = true

[build-dependencies]
forms_build = { path = "../../forms_build" }
